// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vffuulpswwvhsdkuczli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZnV1bHBzd3d2aHNka3VjemxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NzA4MDYsImV4cCI6MjA2NDI0NjgwNn0.QmUJGQwhNFtb5cGtgnVAhqIQ-shammAQUbK7syxsjHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);